### ISSUE TITLE
Full power of Asana API is hidden

### ISSUE THREAD

**Issue by dnesteryuk** [Asana/ruby-asana#16]
Asana API is pretty flexible, but this gem cut offs its flexibility. For example,  we cannot use query tasks by a project && completed_since fields or a tag && completed_since fields.

**Comment by agnoster** [comment]
@txus is there a way to pass query parameters through that I'm missing? It seems like anything passed to `options:` gets `opt_` prepended, which means we can't use it for something like `completed_since`.

**Comment by dnesteryuk** [comment]
Since each API method may have own additional parameters, maybe such parameters can be defined here https://github.com/Asana/asana-api-meta/blob/master/src/resources/task.yaml ? In this case `completed_since` or any other additional parameter can be specified as an argument:

```ruby
  @client.tasks.find_by_project(projectId: project_id, completed_since: 'now')
```

Another solution may be an ability to define own Action generator for actions:

```yaml
- name: findByProject
    method: GET
    path: "/projects/%d/tasks"
    generator: TaskByProject
    params:
      - name: projectId
        <<: *Param.ProjectId
        required: true
        comment: The project in which to search for tasks.
    collection: true
    comment: |
      Returns the compact task records for all tasks within the given project,
      ordered by their priority within the project.  
```

It will inherit and extend the `Action` prototype from https://github.com/Asana/ruby-asana/blob/3879a9f0706c3cecb8e524df9e1bd312450a7ae9/lib/templates/resource.ejs.

The last approach is more flexible, but there are more work to do. This flexibility may help develop more features for this client.

What do you think?
